In [ ]:
import tensorflow as tf
from tensorflow import keras

from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
    'i love my dog',
    'I, love my cat',
    'you love my dog!',
    "Do you think my dog is amazing?"
]

tokenizer = Tokenizer (num_words = 100)
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
word_index

{'my': 1,
 'love': 2,
 'dog': 3,
 'i': 4,
 'you': 5,
 'cat': 6,
 'do': 7,
 'think': 8,
 'is': 9,
 'amazing': 10}

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

sequences = tokenizer.texts_to_sequences(sentences)
print ('\nsequences avant padding:', sequences)

padded_sequences = pad_sequences(sequences,
                                 maxlen=5,
                                 padding='pre')
print('\nséquences après padding (par défaut, padding à la fin):\n', padded_sequences)

print (padded_sequences())


sequences avant padding: [[4, 2, 1, 3], [4, 2, 1, 6], [5, 2, 1, 3], [7, 5, 8, 1, 3, 9, 10]]

séquences après padding (par défaut, padding à la fin):
 [[ 0  4  2  1  3]
 [ 0  4  2  1  6]
 [ 0  5  2  1  3]
 [ 8  1  3  9 10]]


In [ ]:
text_vectorizer = tf.keras.layers.TextVectorization(max_tokens=None,
                                                    standardize = "lower_and_strip_ponctuation",
                                                    split = "whitespace",
                                                    ngrams = None,
                                                    output_mode="int",
                                                    output_sequence_length=None)

In [ ]:
tf.random.set_seed(42)
from tensorflow.keras import layers

embedding = layers.embedding(input_dim=10,
                             output_dim=20,
                             embeddings_initializer="uniform",
                             input_length=10,
                             name="embedding_1")

# Exercice

In [ ]:
import tensorflow as tf
from tensorflow import keras

from tensorflow.keras.preprocessing.text import Tokenizer

sentences= [
    'i am doing my homework', #bon
    'i love this product', #bon
    'he spent a good time with his friends', #bon
    'we are glad to be here', #bon
    'I didnt study for my exam, but i passed it easily', #bon
    'I just finished reading this book, it was amazing, i recommanded it', #bon
    'This application is easy to use', #bon
    'I feel so much better after working out', #bon
    'The quality of the materials is excellent', #bon
    'This comment is very relevant and helped me a lot', #bon
    'The food was cold and tasteless', #mauvais
    'I asked him for a favor, but he shouted at me', #mauvais
    'She was walking outside and she slipped because of the rain', #mauvais
    'Even though i studied hard, I failed my exam', #mauvais
    'The film was horrible, i regret paying to watch it', #mauvais
    'This tutorial is useless', #mauvais
    'I feel depressed and tired', #mauvais
    'Everyone talked about the view, but for us, it was deceiving', #mauvais
    'The staff wasnt welcoming, i am never going back to that restaurant', #mauvais
    'My package was delivered late and damaged', #mauvais
    'The recipe was a disaster, i couldnt make it work' #mauvais
]

labels = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] #1=bon, 0=mauvais

tokenizer = Tokenizer (oov_token="<OOV>", num_words = 100)
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
word_index

{'<OOV>': 1,
 'i': 2,
 'the': 3,
 'was': 4,
 'it': 5,
 'this': 6,
 'and': 7,
 'my': 8,
 'a': 9,
 'to': 10,
 'is': 11,
 'for': 12,
 'but': 13,
 'am': 14,
 'he': 15,
 'exam': 16,
 'feel': 17,
 'of': 18,
 'me': 19,
 'she': 20,
 'doing': 21,
 'homework': 22,
 'love': 23,
 'product': 24,
 'spent': 25,
 'good': 26,
 'time': 27,
 'with': 28,
 'his': 29,
 'friends': 30,
 'we': 31,
 'are': 32,
 'glad': 33,
 'be': 34,
 'here': 35,
 'didnt': 36,
 'study': 37,
 'passed': 38,
 'easily': 39,
 'just': 40,
 'finished': 41,
 'reading': 42,
 'book': 43,
 'amazing': 44,
 'recommanded': 45,
 'application': 46,
 'easy': 47,
 'use': 48,
 'so': 49,
 'much': 50,
 'better': 51,
 'after': 52,
 'working': 53,
 'out': 54,
 'quality': 55,
 'materials': 56,
 'excellent': 57,
 'comment': 58,
 'very': 59,
 'relevant': 60,
 'helped': 61,
 'lot': 62,
 'food': 63,
 'cold': 64,
 'tasteless': 65,
 'asked': 66,
 'him': 67,
 'favor': 68,
 'shouted': 69,
 'at': 70,
 'walking': 71,
 'outside': 72,
 'slipped': 73,
 'because': 

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
sequences = tokenizer.texts_to_sequences(sentences)
print ('\nsequences avant padding:', sequences)

padded_sequences = pad_sequences(sequences,
                                 maxlen=12,
                                 padding='pre')
print('\nséquences après padding (par défaut, padding à la fin):\n', padded_sequences)


sequences avant padding: [[2, 14, 21, 8, 22], [2, 23, 6, 24], [15, 25, 9, 26, 27, 28, 29, 30], [31, 32, 33, 10, 34, 35], [2, 36, 37, 12, 8, 16, 13, 2, 38, 5, 39], [2, 40, 41, 42, 6, 43, 5, 4, 44, 2, 45, 5], [6, 46, 11, 47, 10, 48], [2, 17, 49, 50, 51, 52, 53, 54], [3, 55, 18, 3, 56, 11, 57], [6, 58, 11, 59, 60, 7, 61, 19, 9, 62], [3, 63, 4, 64, 7, 65], [2, 66, 67, 12, 9, 68, 13, 15, 69, 70, 19], [20, 4, 71, 72, 7, 20, 73, 74, 18, 3, 75], [76, 77, 2, 78, 79, 2, 80, 8, 16], [3, 81, 4, 82, 2, 83, 84, 10, 85, 5], [6, 86, 11, 87], [2, 17, 88, 7, 89], [90, 91, 92, 3, 93, 13, 12, 94, 5, 4, 95], [3, 96, 97, 98, 2, 14, 99, 1, 1, 10, 1, 1], [8, 1, 4, 1, 1, 7, 1], [3, 1, 4, 9, 1, 2, 1, 1, 5, 1]]

séquences après padding (par défaut, padding à la fin):
 [[ 0  0  0  0  0  0  0  2 14 21  8 22]
 [ 0  0  0  0  0  0  0  0  2 23  6 24]
 [ 0  0  0  0 15 25  9 26 27 28 29 30]
 [ 0  0  0  0  0  0 31 32 33 10 34 35]
 [ 0  2 36 37 12  8 16 13  2 38  5 39]
 [ 2 40 41 42  6 43  5  4 44  2 45  5]
 [ 0  0  0  0

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GlobalAveragePooling1D, Dense

# Determine vocabulary size (max word index + 1)
vocab_size = len(word_index) + 1

# Determine maximum sequence length from the padded sequences
max_length = padded_sequences.shape[1]

print(f"Taille du vocabulaire: {vocab_size}")
print(f"Longueur maximale de la séquence: {max_length}")

# Convert labels to a numpy array for TensorFlow
labels_array = np.array(labels)

Taille du vocabulaire: 113
Longueur maximale de la séquence: 12


In [ ]:
from tensorflow.keras.layers import Dropout

# Build the model
model = Sequential([
    Embedding(vocab_size, 32, input_length=max_length), # 32 is the embedding dimension
    GlobalAveragePooling1D(), # Averages the embedding vectors of each sequence
    Dropout(0.5), # Add a Dropout layer with a 50% dropout rate
    Dense(16, activation='relu'), # A simple dense layer
    Dense(1, activation='sigmoid') # Output layer for binary classification (0 or 1)
])

# Compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Display the model summary
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d_4      │ ?                      │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Train the model
# We'll use a small number of epochs for this simple example
history = model.fit(padded_sequences, labels_array, epochs=20, verbose=1)

print("\nModèle entraîné avec succès!")

# You can now evaluate the model or make predictions
# For example, to see the accuracy on the training data:
loss, accuracy = model.evaluate(padded_sequences, labels_array, verbose=0)
print(f"Précision sur les données d'entraînement: {accuracy*100:.2f}%")

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.6190 - loss: 0.6921
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5714 - loss: 0.6935
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5238 - loss: 0.6929
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5714 - loss: 0.6927
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7143 - loss: 0.6888
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6190 - loss: 0.6896
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6190 - loss: 0.6892
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6190 - loss: 0.6888
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6190 - loss: 0.6869
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.7143 - loss: 0.6865
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6667 - loss: 0.6874
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7143 - loss: 0.6829
Epo

In [ ]:
test_sentences = [
    "This product is fantastic, I love it!",  # Expected: bon (1)
    "I had a terrible experience with this service.", # Expected: mauvais (0)
    "The movie was okay, not great but not bad either." # Expected: neutral (interpretation needed)
]

# Tokenize the test sentences
test_sequences = tokenizer.texts_to_sequences(test_sentences)
print('\nSéquences de test avant padding:', test_sequences)

# Pad the test sequences
padded_test_sequences = pad_sequences(test_sequences, maxlen=max_length, padding='pre')
print('\nSéquences de test après padding:', padded_test_sequences)

# Make predictions
predictions = model.predict(padded_test_sequences)

print('\nPrédictions (plus proches de 1 pour bon, 0 pour mauvais):')
for i, sentence in enumerate(test_sentences):
    print(f"- \" {sentence} \" -> Prédiction: {predictions[i][0]:.4f}")

# You can interpret predictions as 1 if > 0.5 and 0 if <= 0.5
print('\nInterprétation des prédictions (0 = mauvais, 1 = bon):')
for i, sentence in enumerate(test_sentences):
    sentiment = "bon" if predictions[i][0] > 0.5 else "mauvais"
    print(f"- \" {sentence} \" -> Sentiment: {sentiment} (Score: {predictions[i][0]:.4f})")


Séquences de test avant padding: [[6, 24, 11, 1, 2, 23, 5], [2, 1, 9, 1, 1, 28, 6, 1], [3, 1, 4, 1, 1, 1, 13, 1, 1, 1]]

Séquences de test après padding: [[ 0  0  0  0  0  6 24 11  1  2 23  5]
 [ 0  0  0  0  2  1  9  1  1 28  6  1]
 [ 0  0  3  1  4  1  1  1 13  1  1  1]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Prédictions (plus proches de 1 pour bon, 0 pour mauvais):
- " This product is fantastic, I love it! " -> Prédiction: 0.4930
- " I had a terrible experience with this service. " -> Prédiction: 0.4832
- " The movie was okay, not great but not bad either. " -> Prédiction: 0.4631

Interprétation des prédictions (0 = mauvais, 1 = bon):
- " This product is fantastic, I love it! " -> Sentiment: mauvais (Score: 0.4930)
- " I had a terrible experience with this service. " -> Sentiment: mauvais (Score: 0.4832)
- " The movie was okay, not great but not bad either. " -> Sentiment: mauvais (Score: 0.4631)


# Exercice : Sarcasm dataset

In [ ]:
# Step 1: Install the gdown library
!pip install gdown

# Step 2: Use gdown to download the file and name it "sarcasm.json"
!gdown --id 1xRU3xY5-tkiPGvlz5xBJ18_pHWSRzI4v -O sarcasm.json

# Step 3: Now your pandas code will work
import json
import pandas as pd

data = pd.read_json("./sarcasm.json")
data.head()

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1xRU3xY5-tkiPGvlz5xBJ18_pHWSRzI4v
To: /content/sarcasm.json
100% 5.64M/5.64M [00:00<00:00, 67.5MB/s]


article_link  \
0  https://www.huffingtonpost.com/entry/versace-b...   
1  https://www.huffingtonpost.com/entry/roseanne-...   
2  https://local.theonion.com/mom-starting-to-fea...   
3  https://politics.theonion.com/boehner-just-wan...   
4  https://www.huffingtonpost.com/entry/jk-rowlin...   

                                            headline  is_sarcastic  
0  former versace store clerk sues over secret 'b...             0  
1  the 'roseanne' revival catches up to our thorn...             0  
2  mom starting to fear son's web series closest ...             1  
3  boehner just wants wife to listen, not come up...             1  
4  j.k. rowling wishes snape happy birthday in th...             0

In [ ]:
import json
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np


# Extract headlines and labels
sarcasm_sentences = data['headline'].tolist()
sarcasm_labels = data['is_sarcastic'].tolist()

print(f"Nombre total de phrases: {len(sarcasm_sentences)}")
print(f"Nombre total de labels: {len(sarcasm_labels)}")
print("Premières 5 headlines:", sarcasm_sentences[:5])
print("Premiers 5 labels:", sarcasm_labels[:5])

Nombre total de phrases: 26709
Nombre total de labels: 26709
Premières 5 headlines: ["former versace store clerk sues over secret 'black code' for minority shoppers", "the 'roseanne' revival catches up to our thorny political mood, for better and worse", "mom starting to fear son's web series closest thing she will have to grandchild", 'boehner just wants wife to listen, not come up with alternative debt-reduction ideas', 'j.k. rowling wishes snape happy birthday in the most magical way']
Premiers 5 labels: [0, 0, 1, 1, 0]


In [ ]:
# Option recommandée : Garder '!' et '?'
num_words = 10000
tokenizer_sarcasm = Tokenizer(
    num_words=num_words,
    # J'ai retiré ! et ? de la liste ci-dessous
    filters='"#$%&()*+,-./:;<=>@[\\]^_`{|}~\t\n',
    oov_token="<OOV>",
    lower=True
)

# Le reste de votre code est identique
tokenizer_sarcasm.fit_on_texts(sarcasm_sentences)
word_index_sarcasm = tokenizer_sarcasm.word_index

# Vous verrez maintenant '!' et '?' dans votre word_index !
print(f"Taille du vocabulaire (incluant OOV): {len(word_index_sarcasm)}")
print(word_index_sarcasm)

Taille du vocabulaire (incluant OOV): 30392
{'<OOV>': 1, 'to': 2, 'of': 3, 'the': 4, 'in': 5, 'for': 6, 'a': 7, 'on': 8, 'and': 9, 'with': 10, 'is': 11, 'new': 12, 'trump': 13, 'man': 14, 'from': 15, 'at': 16, 'about': 17, 'you': 18, 'by': 19, 'this': 20, 'after': 21, 'out': 22, 'up': 23, 'be': 24, 'how': 25, 'as': 26, 'that': 27, 'it': 28, 'not': 29, 'are': 30, 'your': 31, 'his': 32, 'what': 33, 'he': 34, 'all': 35, 'just': 36, 'who': 37, 'has': 38, 'will': 39, 'more': 40, 'one': 41, 'into': 42, 'report': 43, 'year': 44, 'why': 45, 'have': 46, 'area': 47, 'over': 48, 'donald': 49, 'u': 50, 'day': 51, 'says': 52, 's': 53, 'can': 54, 'first': 55, 'woman': 56, 'time': 57, 'like': 58, 'her': 59, "trump's": 60, 'old': 61, 'get': 62, 'no': 63, 'off': 64, 'an': 65, 'life': 66, 'people': 67, 'obama': 68, 'now': 69, 'house': 70, 'still': 71, 'make': 72, 'women': 73, 'was': 74, 'than': 75, 'white': 76, 'my': 77, 'back': 78, 'i': 79, 'clinton': 80, 'if': 81, 'down': 82, '5': 83, 'when': 84, 'cou

In [ ]:
# Convert sentences to sequences of numbers
sarcasm_sequences = tokenizer_sarcasm.texts_to_sequences(sarcasm_sentences)

# Determine maximum sequence length (for padding)
# You might want to choose a maxlen based on the distribution of sequence lengths
max_sequence_length_sarcasm = max([len(x) for x in sarcasm_sequences])
print(f"Longueur maximale de séquence trouvée: {max_sequence_length_sarcasm}")

# Apply padding to the sequences
# Using 'post' padding is common for NLP tasks before feed-forward layers
padded_sarcasm_sequences = pad_sequences(sarcasm_sequences,
                                         maxlen=max_sequence_length_sarcasm,
                                         padding='post',
                                         truncating='post') # Truncate long sequences from the end

print("Premières 5 séquences après padding:\n", padded_sarcasm_sequences[:5])
print(f"Forme des séquences paddées: {padded_sarcasm_sequences.shape}")

# Convert labels to numpy array
sarcasm_labels_array = np.array(sarcasm_labels)
print(f"Forme des labels: {sarcasm_labels_array.shape}")

Longueur maximale de séquence trouvée: 40
Premières 5 séquences après padding:
 [[  308 15115   679  3337  2298    48   382  2576 15116     6  2577  8434
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0]
 [    4  8435  3338  2746    22     2   166  8436   416  3112     6   258
      9  1002     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0]
 [  145   838     2   907  1749  2093   582  4719   221   143    39    46
      2 10736     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0]
 [ 1485    36   224   400     2  1832    29   319    22    10  2924  1393
   6969   968     0     0     0     0     0     0     0     0     0     0
      0     0     0     0

Split données

In [ ]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding, GlobalAveragePooling1D

# Vos variables de l'étape précédente (assurez-vous qu'elles sont définies)
# num_words = 10000
# max_sequence_length_sarcasm = 40 # (Ou la valeur que vous avez choisie)
# padded_sarcasm_sequences
# sarcasm_labels_array

# Diviser les données
X_train, X_test, y_train, y_test = train_test_split(
    padded_sarcasm_sequences,
    sarcasm_labels_array,
    test_size=0.2,    # 20% pour le test
    random_state=42   # Pour garantir des résultats reproductibles
)

print(f"Taille de l'ensemble d'entraînement: {len(X_train)}")
print(f"Taille de l'ensemble de test: {len(X_test)}")

Taille de l'ensemble d'entraînement: 21367
Taille de l'ensemble de test: 5342


Modèle 1

In [ ]:
# Construction du Modèle 1
model_1 = Sequential([
    # Aplatir les séquences (maxlen,) en un seul grand vecteur (maxlen)
    # Si maxlen=40, on aura un vecteur de 40 entrées.
    Flatten(input_shape=(max_sequence_length_sarcasm,)),

    # Couches denses classiques
    Dense(16, activation='relu'),
    Dense(8, activation='relu'),

    # Couche de sortie : 1 neurone (0 ou 1) avec sigmoïde
    Dense(1, activation='sigmoid')
])

model_1.summary()

# Compilation
model_1.compile(
    loss='binary_crossentropy', # Parfait pour la classification binaire (0/1)
    optimizer='adam',
    metrics=['accuracy']
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten (Flatten)               │ (None, 40)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 16)             │           656 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 801 (3.13 KB)

 Trainable params: 801 (3.13 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Entraînement
print("\n--- Entraînement Modèle 1 (Sans Embedding) ---")
history_1 = model_1.fit(
    X_train,
    y_train,
    epochs=10,               # 10 passages sur les données
    batch_size=32,
    validation_data=(X_test, y_test), # Évaluation sur les données de test à chaque époque
    verbose=1
)

# Évaluation finale
print("\n--- Évaluation Modèle 1 ---")
loss_1, accuracy_1 = model_1.evaluate(X_test, y_test)
print(f"Précision Modèle 1 (Sans Embedding): {accuracy_1 * 100:.2f}%")


--- Entraînement Modèle 1 (Sans Embedding) ---
Epoch 1/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.5071 - loss: 85.1319 - val_accuracy: 0.5477 - val_loss: 2.6655
Epoch 2/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5462 - loss: 1.5910 - val_accuracy: 0.5543 - val_loss: 0.9388
Epoch 3/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5570 - loss: 0.7154 - val_accuracy: 0.5588 - val_loss: 0.8041
Epoch 4/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5610 - loss: 0.6912 - val_accuracy: 0.5612 - val_loss: 0.7980
Epoch 5/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5534 - loss: 0.6897 - val_accuracy: 0.5605 - val_loss: 0.7916
Epoch 6/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5600 - loss: 0.6861 - val_accuracy: 0.5603 - val_loss: 0.7893
Epoch 7/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5581 - loss: 0.6873 - val_accuracy: 0.5595 - val_loss: 0.7856
Epoch 8/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - a

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

# --- Mettez vos phrases de test ici ---
test_phrases = [
    "Oh, great. Another meeting. My day is complete.", # Exemple sarcastique
    "The new restaurant has amazing food and great service.", # Exemple non sarcastique
    "I just love it when my code breaks at 5 PM on a Friday.", # Exemple sarcastique
    "The weather is really nice today." # Exemple non sarcastique
]

# 1. Tokeniser les nouvelles phrases (convertir en chiffres)
test_sequences = tokenizer_sarcasm.texts_to_sequences(test_phrases)

# 2. Paddler les séquences (même longueur que l'entraînement)
test_padded = pad_sequences(test_sequences,
                            maxlen=max_sequence_length_sarcasm,
                            padding='post',
                            truncating='post')

# 3. Prédiction avec le Modèle 1
predictions_1 = model_1.predict(test_padded)

# 4. Afficher les résultats
print("--- Résultats du Modèle 1 (Sans Embedding) ---")
for i in range(len(test_phrases)):
    print(f"\nPhrase: {test_phrases[i]}")
    prob = predictions_1[i][0] # Probabilité brute (ex: 0.512)
    sentiment = "Sarcastique" if prob > 0.5 else "Non Sarcastique"
    print(f"-> Résultat: {sentiment} (Probabilité: {prob*100:.2f}%)")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step
--- Résultats du Modèle 1 (Sans Embedding) ---

Phrase: Oh, great. Another meeting. My day is complete.
-> Résultat: Non Sarcastique (Probabilité: 44.23%)

Phrase: The new restaurant has amazing food and great service.
-> Résultat: Non Sarcastique (Probabilité: 44.23%)

Phrase: I just love it when my code breaks at 5 PM on a Friday.
-> Résultat: Non Sarcastique (Probabilité: 44.23%)

Phrase: The weather is really nice today.
-> Résultat: Non Sarcastique (Probabilité: 44.23%)


Modèle 2

In [ ]:
# Obtenir la taille RÉELLE du vocabulaire à partir du tokenizer
# +1 pour réserver l'index 0 pour le padding
vocab_size = len(word_index_sarcasm) + 1
embedding_dim = 16

model_2 = Sequential([
    # La correction est ici :
    Embedding(
        input_dim=vocab_size,         # <--- UTILISER LA TAILLE RÉELLE
        output_dim=embedding_dim,
        input_length=max_sequence_length_sarcasm
    ),

    GlobalAveragePooling1D(),
    Dense(16, activation='relu'),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

model_2.summary()

# La compilation ne change pas
model_2.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)


Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d_7      │ ?                      │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:

# L'entraînement devrait maintenant fonctionner
print("\n--- Entraînement Modèle 2 (Corrigé) ---")
history_2 = model_2.fit(
    X_train,
    y_train,
    epochs=10,
    batch_size=32,
    validation_data=(X_test, y_test),
    verbose=1
)

# L'évaluation ne change pas
print("\n--- Évaluation Modèle 2 ---")
loss_2, accuracy_2 = model_2.evaluate(X_test, y_test)
print(f"Précision Modèle 2 (Avec Embedding): {accuracy_2 * 100:.2f}%")


--- Entraînement Modèle 2 (Corrigé) ---
Epoch 1/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.5660 - loss: 0.6763 - val_accuracy: 0.8272 - val_loss: 0.4327
Epoch 2/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.8394 - loss: 0.3803 - val_accuracy: 0.8521 - val_loss: 0.3498
Epoch 3/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.8931 - loss: 0.2727 - val_accuracy: 0.8589 - val_loss: 0.3297
Epoch 4/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9203 - loss: 0.2129 - val_accuracy: 0.8218 - val_loss: 0.4180
Epoch 5/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9377 - loss: 0.1698 - val_accuracy: 0.8602 - val_loss: 0.3486
Epoch 6/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9507 - loss: 0.1382 - val_accuracy: 0.8575 - val_loss: 0.3656
Epoch 7/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9610 - loss: 0.1150 - val_accuracy: 0.8525 - val_loss: 0.4006
Epoch 8/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy:

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

# --- Les mêmes phrases de test ---
# (Vous pouvez les redéfinir ou réutiliser les variables de la cellule ci-dessus)
test_phrases = [
    "Oh, great. Another meeting. My day is complete.", # Exemple sarcastique
    "The new restaurant has amazing food and great service.", # Exemple non sarcastique
    "I just love it when my code breaks at 5 PM on a Friday.", # Exemple sarcastique
    "The weather is really nice today." # Exemple non sarcastique
]

# 1. Tokeniser les nouvelles phrases (convertir en chiffres)
test_sequences = tokenizer_sarcasm.texts_to_sequences(test_phrases)

# 2. Paddler les séquences (même longueur que l'entraînement)
test_padded = pad_sequences(test_sequences,
                            maxlen=max_sequence_length_sarcasm,
                            padding='post',
                            truncating='post')

# 3. Prédiction avec le Modèle 2
predictions_2 = model_2.predict(test_padded)

# 4. Afficher les résultats
print("--- Résultats du Modèle 2 (Avec Embedding) ---")
for i in range(len(test_phrases)):
    print(f"\nPhrase: {test_phrases[i]}")
    prob = predictions_2[i][0] # Probabilité brute (ex: 0.981)
    sentiment = "Sarcastique" if prob > 0.5 else "Non Sarcastique"
    print(f"-> Résultat: {sentiment} (Probabilité: {prob*100:.2f}%)")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 239ms/step
--- Résultats du Modèle 2 (Avec Embedding) ---

Phrase: Oh, great. Another meeting. My day is complete.
-> Résultat: Non Sarcastique (Probabilité: 6.46%)

Phrase: The new restaurant has amazing food and great service.
-> Résultat: Non Sarcastique (Probabilité: 1.08%)

Phrase: I just love it when my code breaks at 5 PM on a Friday.
-> Résultat: Non Sarcastique (Probabilité: 2.64%)

Phrase: The weather is really nice today.
-> Résultat: Non Sarcastique (Probabilité: 0.02%)


In [ ]:
# Relancez l'entraînement avec plus d'époques
history_2 = model_2.fit(
    X_train,
    y_train,
    epochs=30,  # <--- Augmentez ceci
    batch_size=32,
    validation_data=(X_test, y_test),
    verbose=1
)

Epoch 1/30
668/668 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9853 - loss: 0.0484 - val_accuracy: 0.8416 - val_loss: 0.5478
Epoch 2/30
668/668 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.9873 - loss: 0.0415 - val_accuracy: 0.8321 - val_loss: 0.6108
Epoch 3/30
668/668 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9857 - loss: 0.0439 - val_accuracy: 0.8261 - val_loss: 0.7231
Epoch 4/30
668/668 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9909 - loss: 0.0314 - val_accuracy: 0.8358 - val_loss: 0.6481
Epoch 5/30
668/668 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9924 - loss: 0.0234 - val_accuracy: 0.8345 - val_loss: 0.6975
Epoch 6/30
668/668 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9928 - loss: 0.0243 - val_accuracy: 0.8334 - val_loss: 0.7204
Epoch 7/30
668/668 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9910 - loss: 0.0260 - val_accuracy: 0.8261 - val_loss: 0.7873
Epoch 8/30
668/668 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9940 - loss: 0.0187 - val_accuracy: 0

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

# --- Les mêmes phrases de test ---
# (Vous pouvez les redéfinir ou réutiliser les variables de la cellule ci-dessus)
test_phrases = [
    "Oh, great. Another meeting. My day is complete.", # Exemple sarcastique
    "The new restaurant has amazing food and great service.", # Exemple non sarcastique
    "I just love it when my code breaks at 5 PM on a Friday.", # Exemple sarcastique
    "The weather is really nice today." # Exemple non sarcastique
]

# 1. Tokeniser les nouvelles phrases (convertir en chiffres)
test_sequences = tokenizer_sarcasm.texts_to_sequences(test_phrases)

# 2. Paddler les séquences (même longueur que l'entraînement)
test_padded = pad_sequences(test_sequences,
                            maxlen=max_sequence_length_sarcasm,
                            padding='post',
                            truncating='post')

# 3. Prédiction avec le Modèle 2
predictions_2 = model_2.predict(test_padded)

# 4. Afficher les résultats
print("--- Résultats du Modèle 2 (Avec Embedding) ---")
for i in range(len(test_phrases)):
    print(f"\nPhrase: {test_phrases[i]}")
    prob = predictions_2[i][0] # Probabilité brute (ex: 0.981)
    sentiment = "Sarcastique" if prob > 0.5 else "Non Sarcastique"
    print(f"-> Résultat: {sentiment} (Probabilité: {prob*100:.2f}%)")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
--- Résultats du Modèle 2 (Avec Embedding) ---

Phrase: Oh, great. Another meeting. My day is complete.
-> Résultat: Sarcastique (Probabilité: 83.28%)

Phrase: The new restaurant has amazing food and great service.
-> Résultat: Non Sarcastique (Probabilité: 0.00%)

Phrase: I just love it when my code breaks at 5 PM on a Friday.
-> Résultat: Non Sarcastique (Probabilité: 0.00%)

Phrase: The weather is really nice today.
-> Résultat: Non Sarcastique (Probabilité: 0.00%)


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GlobalAveragePooling1D, Dense, Dropout
import numpy as np

# Define vocabulary size and max length for the sarcasm dataset
vocab_size_sarcasm = len(word_index_sarcasm) + 1 # +1 for OOV token or padding
max_length_sarcasm = padded_sarcasm_sequences.shape[1]

print(f"Taille du vocabulaire pour le sarcasme: {vocab_size_sarcasm}")
print(f"Longueur maximale de la séquence pour le sarcasme: {max_length_sarcasm}")

# Build the sarcasm detection model
sarcasm_model = Sequential([
    Embedding(vocab_size_sarcasm, 64, input_length=max_length_sarcasm), # Embedding dimension of 64
    GlobalAveragePooling1D(),
    Dropout(0.5), # Add Dropout to combat overfitting
    Dense(32, activation='relu'), # A dense layer
    Dense(1, activation='sigmoid') # Output layer for binary classification
])

# Compile the model
sarcasm_model.compile(optimizer='adam',
                      loss='binary_crossentropy',
                      metrics=['accuracy'])

# Display the model summary
sarcasm_model.summary()

Taille du vocabulaire pour le sarcasme: 29658
Longueur maximale de la séquence pour le sarcasme: 40


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d_5      │ ?                      │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Train the sarcasm detection model
# Using a larger dataset, we might need more epochs and a validation split
num_epochs = 10
history_sarcasm = sarcasm_model.fit(padded_sarcasm_sequences,
                                    sarcasm_labels_array,
                                    epochs=num_epochs,
                                    validation_split=0.2, # Use 20% of data for validation
                                    verbose=1)

print("\nModèle de détection de sarcasme entraîné avec succès!")

# Evaluate the model on the training and validation data
loss_train, accuracy_train = sarcasm_model.evaluate(padded_sarcasm_sequences, sarcasm_labels_array, verbose=0)
print(f"Précision sur les données d'entraînement (sarcasme): {accuracy_train*100:.2f}%")

Epoch 1/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 14s 18ms/step - accuracy: 0.5966 - loss: 0.6564 - val_accuracy: 0.8154 - val_loss: 0.4232
Epoch 2/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 12s 18ms/step - accuracy: 0.8264 - loss: 0.3908 - val_accuracy: 0.8298 - val_loss: 0.3719
Epoch 3/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 13s 19ms/step - accuracy: 0.8816 - loss: 0.2856 - val_accuracy: 0.8516 - val_loss: 0.3463
Epoch 4/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 12s 18ms/step - accuracy: 0.9045 - loss: 0.2381 - val_accuracy: 0.8596 - val_loss: 0.3402
Epoch 5/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 12s 18ms/step - accuracy: 0.9291 - loss: 0.1870 - val_accuracy: 0.8428 - val_loss: 0.3946
Epoch 6/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 12s 18ms/step - accuracy: 0.9365 - loss: 0.1664 - val_accuracy: 0.8536 - val_loss: 0.3810
Epoch 7/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 12s 18ms/step - accuracy: 0.9500 - loss: 0.1349 - val_accuracy: 0.8521 - val_loss: 0.3855
Epoch 8/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 20s 18ms/step - accuracy: 0.9580 - loss: 0.1184 - 

-----------------------------------------

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

# --- Step 1: Create and adapt TextVectorization layer ---
# This layer will handle tokenization and converting text to a binary vector representation
# without an explicit Embedding layer.

# We'll use the same num_words (max_tokens) as defined for the previous tokenizer
# For simplicity, let's use the vocab size from tokenizer_sarcasm, but it can be adjusted.
max_features = len(word_index_sarcasm) + 1 # Max number of unique words to consider, +1 for OOV/padding
output_sequence_length = max_length_sarcasm # The length of the output vector per sample

text_vectorizer_no_emb = tf.keras.layers.TextVectorization(
    max_tokens=max_features,
    output_mode='binary', # Output a multi-hot binary vector of the words present
    # output_mode='tf_idf' could also be used for a more nuanced representation
    output_sequence_length=output_sequence_length # This will pad/truncate the binary vector
)

# Adapt the layer to your training data (sarcasm_sentences - raw text)
text_vectorizer_no_emb.adapt(sarcasm_sentences)

print(f"Vocabulaire adapté par TextVectorization (extrait):\n{text_vectorizer_no_emb.get_vocabulary()[:10]}")
print(f"Taille du vocabulaire de TextVectorization: {len(text_vectorizer_no_emb.get_vocabulary())}")

In [ ]:
# --- Step 2: Build the model WITHOUT Embedding layer ---
sarcasm_model_no_emb = Sequential([
    text_vectorizer_no_emb, # The first layer is now the TextVectorization layer
    Dense(32, activation='relu'), # A simple dense layer
    Dropout(0.5), # Add Dropout to combat overfitting
    Dense(1, activation='sigmoid') # Output layer for binary classification
])

# Compile the model
sarcasm_model_no_emb.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Display the model summary
print("\n--- Résumé du Modèle SANS Couche d'Embedding ---")
sarcasm_model_no_emb.summary()

### Explication des Paramètres et Entraînement

Comme discuté précédemment, `model.summary()` affiche le **nombre de paramètres** entraînés par couche, et non leurs valeurs. Pour voir les valeurs réelles des poids et des biais *après l'entraînement* (car ils sont ajustés pendant ce processus), nous utiliserons la méthode `get_weights()` sur le modèle.

Nous allons maintenant entraîner ce modèle. Notez que l'entrée de `sarcasm_model_no_emb.fit()` est `sarcasm_sentences` (le texte brut), car la couche `TextVectorization` s'occupe de la vectorisation interne.

In [ ]:
# --- Step 3: Train the model WITHOUT Embedding layer ---
num_epochs_no_emb = 10
history_sarcasm_no_emb = sarcasm_model_no_emb.fit(
    sarcasm_sentences, # Input is raw sentences
    sarcasm_labels_array,
    epochs=num_epochs_no_emb,
    validation_split=0.2, # Use 20% of data for validation
    verbose=1
)

print("\nModèle SANS Couche d'Embedding entraîné avec succès!")

# Evaluate the model on the training data
loss_no_emb, accuracy_no_emb = sarcasm_model_no_emb.evaluate(sarcasm_sentences, sarcasm_labels_array, verbose=0)
print(f"Précision sur les données d'entraînement (Modèle SANS Embedding): {accuracy_no_emb*100:.2f}%")

# --- Step 4: Access and display model parameters (weights/biases) ---
print("\n--- Accès aux Poids et Biais du Modèle SANS Couche d'Embedding (après entraînement) ---")

# Weights for the first Dense layer (index 1 after TextVectorization)
print("\nPoids de la première couche Dense (extrait):\n")
weights_dense1 = sarcasm_model_no_emb.layers[1].get_weights()[0] # get_weights()[0] for weights
biases_dense1 = sarcasm_model_no_emb.layers[1].get_weights()[1] # get_weights()[1] for biases
print(f"Forme des poids de la couche Dense: {weights_dense1.shape}")
print(f"Premières 5 valeurs de poids de la couche Dense:\n{weights_dense1.flatten()[:5]}")
print(f"Biais de la couche Dense:\n{biases_dense1}")

# Weights for the output Dense layer (index 3 after TextVectorization, Dense, Dropout)
print("\nPoids de la couche de sortie (extrait):\n")
weights_output = sarcasm_model_no_emb.layers[3].get_weights()[0]
biases_output = sarcasm_model_no_emb.layers[3].get_weights()[1]
print(f"Forme des poids de la couche de sortie: {weights_output.shape}")
print(f"Poids de la couche de sortie:\n{weights_output.flatten()}")
print(f"Biais de la couche de sortie:\n{biases_output}")

### Modèle de Classification AVEC Couche d'Embedding

Maintenant, nous allons construire un deuxième modèle, cette fois en utilisant une couche `Embedding`. Ce modèle prendra en entrée les séquences d'entiers que nous avons déjà générées (`padded_sarcasm_sequences`).

Nous allons définir la même architecture de base, mais avec la couche `Embedding` en premier, suivie de `GlobalAveragePooling1D`, `Dropout` et des couches `Dense`.


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GlobalAveragePooling1D, Dense, Dropout
import numpy as np

# Define vocabulary size and max length for the sarcasm dataset
vocab_size_sarcasm = len(word_index_sarcasm) + 1 # +1 for OOV token or padding
max_length_sarcasm = padded_sarcasm_sequences.shape[1]

print(f"Taille du vocabulaire pour le sarcasme: {vocab_size_sarcasm}")
print(f"Longueur maximale de la séquence pour le sarcasme: {max_length_sarcasm}")

# --- Step 1: Build the model WITH Embedding layer ---
sarcasm_model_with_emb = Sequential([
    Embedding(vocab_size_sarcasm, 64, input_length=max_length_sarcasm), # Embedding dimension of 64
    GlobalAveragePooling1D(),
    Dropout(0.5), # Add Dropout to combat overfitting
    Dense(32, activation='relu'), # A dense layer
    Dense(1, activation='sigmoid') # Output layer for binary classification
])

# Compile the model
sarcasm_model_with_emb.compile(optimizer='adam',
                               loss='binary_crossentropy',
                               metrics=['accuracy'])

# Display the model summary
print("\n--- Résumé du Modèle AVEC Couche d'Embedding ---")
sarcasm_model_with_emb.summary()

### Entraînement du Modèle AVEC Couche d'Embedding

Nous allons maintenant entraîner ce modèle. Il prendra en entrée les `padded_sarcasm_sequences` (séquences d'entiers).


In [ ]:
# --- Step 2: Train the model WITH Embedding layer ---
num_epochs_with_emb = 10
history_sarcasm_with_emb = sarcasm_model_with_emb.fit(
    padded_sarcasm_sequences, # Input is padded integer sequences
    sarcasm_labels_array,
    epochs=num_epochs_with_emb,
    validation_split=0.2, # Use 20% of data for validation
    verbose=1
)

print("\nModèle AVEC Couche d'Embedding entraîné avec succès!")

# Evaluate the model on the training data
loss_with_emb, accuracy_with_emb = sarcasm_model_with_emb.evaluate(padded_sarcasm_sequences, sarcasm_labels_array, verbose=0)
print(f"Précision sur les données d'entraînement (Modèle AVEC Embedding): {accuracy_with_emb*100:.2f}%")

# --- Step 3: Access and display model parameters (weights/biases) ---
print("\n--- Accès aux Poids et Biais du Modèle AVEC Couche d'Embedding (après entraînement) ---")

# Weights for the Embedding layer
print("\nPoids de la couche Embedding (premières 5 entrées):\n")
embedding_weights_emb = sarcasm_model_with_emb.layers[0].get_weights()[0]
print(embedding_weights_emb[:5]) # Afficher les 5 premières lignes des poids d'embedding

# Weights for the first Dense layer (index 2 after Embedding, GlobalAveragePooling1D)
print("\nPoids et biais de la première couche Dense (une partie):\n")
dense_layer_weights_emb = sarcasm_model_with_emb.layers[2].get_weights()
print(f"Poids de la couche Dense:\n{dense_layer_weights_emb[0][:5, :5]}") # Afficher une partie du tableau
print(f"Biais de la couche Dense:\n{dense_layer_weights_emb[1]}")
